language: node_js
node_js:
  - "4.2"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  - CXX=g++-4.8

before_script:
  - npm install -g bower
  - bower install
  - tsd install

script:
  - gulp build

